### ISSUE TITLE
Subtitles for non-NPCs (e.g. radios) do not display correctly.

### ISSUE THREAD

**Issue by HinataNatsumi** [hzqst/CaptionMod#10]
Subtitles for non-NPCs (e.g. radios) do not display correctly. Affects the version 3.4 and 3.5.

Mostly affects radios. Strangely, announcements are not affected. Sometimes it can delay and start playing from the next line, but if so, short lines may never play. If cap_show 1 is set, it says the subtitle was found correctly, as seen on the demonstration video.

Demonstration video for the bug: (Taken in _Opposing Force_, but also confirmed on _Half-Life_.)
[https://youtu.be/ZPtieRK2ETo](url)

**Comment by hzqst** [comment]
What is the levelname in the video?

**Comment by HinataNatsumi** [comment]
> What is the levelname in the video?

Opposing Force: of1a2 (also may happen on of0a0, the intro map)

In Half-Life, I checked c2a5g.

**Comment by hzqst** [comment]
I am not able to reproduce the issue with chinese translation of radio, could you please provide your subtitle config files and dictionary files?

**Comment by HinataNatsumi** [comment]
> I am not able to reproduce the issue with chinese translation of radio, could you please provide your subtitle config files and dictionary files?

Okay, I’ve included all the files (including the dll files too) to help you reproduce the bugs.

I used the .bat file startup-gearbox.bat to start the game.

https://drive.google.com/file/d/1YZXZkUtOg7nIPMXEtGoXLiJKA4RakMc7/view?usp=sharing

**Comment by hzqst** [comment]
Should be fixed with latest commit.
![20210308144927](https://user-images.githubusercontent.com/12287588/110284966-8349f080-801d-11eb-8d20-bff07329a51c.png)

**Comment by HinataNatsumi** [comment]
> Should be fixed with latest commit.

Thank you so much for the quick fix. Any chance you’ll update the binary as well?

**Comment by hzqst** [comment]
> > Should be fixed with latest commit.
> 
> Thank you so much for the quick fix. Any chance you’ll update the binary as well?

committed

**Comment by HinataNatsumi** [comment]
> > > Should be fixed with latest commit.
> > 
> > 
> > Thank you so much for the quick fix. Any chance you’ll update the binary as well?
> 
> committed

Thank you! You rock. Thanks again for such a great mod. I’ll close this issue now.
