### ISSUE TITLE
CZ零点行动无法进入单人任务模式

### ISSUE THREAD

**Issue by q52888940** [hzqst/CaptionMod#13]
我目前正在为CZ零点行动制作任务包 但我安装了插件后无法进入任务模式了 我对编码编写不是很熟悉 所以想问以后会不会更新解决这个问题。
另外 无线电的宿主该怎么找到，AMXX加载的wav声音该怎么被获取到

**Comment by hzqst** [comment]
![cz](https://user-images.githubusercontent.com/12287588/125259212-ae2cb400-e331-11eb-859d-cf85bd4df85f.png)

↑直接从github下的最新版本，发现没有任何问题

**Comment by q52888940** [comment]
我指的不是单人任务，而是CS零点行动的一个与BOT作战的任务，请你进入CS零点行动并且点击开始游戏反恐精英:零点行动进入CZ任务包尝试会不会崩溃
![B6IX($3QK0%KEFL6E5CLQVD](https://user-images.githubusercontent.com/68973128/125259730-2e531980-e332-11eb-86f1-84b9b21fa821.png)

**Comment by q52888940** [comment]
你是否会在下次更新中修复它

**Comment by hzqst** [comment]
经验证发现是GameUI.dll+0x117F处的代码向scheme manager中传递了一个空字符串，即请求获取的图像名称为空字符串（""）

![image](https://user-images.githubusercontent.com/12287588/125265185-2b0e5c80-e337-11eb-9879-8b833eb681f5.png)

被hook后的CSchemeManager::GetImage给该图像返回了一个空指针

![image](https://user-images.githubusercontent.com/12287588/125265434-6b6dda80-e337-11eb-921d-bd1f5f33be82.png)

后续GameUI.dll+1491处有对该空指针进行引用，导致游戏崩溃

![image](https://user-images.githubusercontent.com/12287588/125265610-95270180-e337-11eb-9c4e-1c0ffa34ff4b.png)

而v社自己版本的vgui2.dll!CSchemeManager::GetImage中未对空字符串返回空指针所以后续流程不会崩溃

最新的 commit f3a68d9 （代码变更） 和 f220a9e （更新的dll文件）应该解决了此问题，请查收。

**Comment by q52888940** [comment]
非常感谢你的帮助 但我使用VS2019/2013都无法编译，你是否能直接向我提供DLL文件

**Comment by hzqst** [comment]
> 非常感谢你的帮助 但我使用VS2019/2013都无法编译，你是否能直接向我提供DLL文件

f220a9e 就是更新的dll文件

**Comment by q52888940** [comment]
好的 再次感谢
