### ISSUE TITLE
我该如何显示消息是谁发出的

### ISSUE THREAD

**Issue by q52888940** [hzqst/CaptionMod#14]
在CS零点行动中 我如何找到声音发出的玩家是谁

**Comment by hzqst** [comment]
ae8441b 增加了对SendAudio的支持，收到无线电的时候也可以显示字幕

范例：
![image](https://user-images.githubusercontent.com/12287588/125290149-94e82f80-e352-11eb-8ed7-07b3fa3ff973.png)

`<sender>`会被替换为无线电发送者的名字

提示：如果需要获得其他无线电的代码请打开`cap_debug 1`去控制台查看

**Comment by q52888940** [comment]
我已经下载了最新版本 但我不懂怎么写这个 是写在csv文件中吗 并且我在控制台输入CAP_DEBUG 1显示命令无效

**Comment by hzqst** [comment]
写在csv文件中，按上图中格式即可，如果cap_debug提示不支持的命令说明你的CaptionMod插件未加载成功。

**Comment by q52888940** [comment]
你能否写出来格式，我在CSV中写 %!MRAD_GO,<sender>,SkyBLue,#RADIO_GO,,,,,, 无效

**Comment by q52888940** [comment]
你可以解决这个问题吗 我试了好几种都是语法错误

**Comment by hzqst** [comment]
建议用Microsoft Excel编辑，保证格式是
![image](https://user-images.githubusercontent.com/12287588/126292255-0742b8fd-8b9f-49db-8142-9d5aef79066e.png)
这样的即可

建议打开cap_debug 1看CaptionMod能否捕获到该无线电，如果可以的话应该没问题的

**Comment by hzqst** [comment]
效果应该如图

![2222](https://user-images.githubusercontent.com/12287588/126292668-f896b017-a07a-4e07-858e-ea5b950d3685.png)
![3333](https://user-images.githubusercontent.com/12287588/126292673-2ccd6837-8e4d-431b-a1d4-8352ac149f79.png)

**Comment by q52888940** [comment]
好的 那么在这请教最后一个问题 如何把名字显示在RADIO的前方 我尝试换位置 但无效，一个句子中不能使用两个不同的颜色文字吗比如"你好"你是蓝色，好是黄色

**Comment by hzqst** [comment]
想要把名字显示在RADIO的前方，只需要在把Speaker条目下的[Radio]挪到正文文本（即Translation）中即可
![image](https://user-images.githubusercontent.com/12287588/126323823-168a4d61-2d2a-497b-848c-8759cc5a46f6.png)

一个句子中目前暂不支持两种颜色，后续应该会增加支持

**Comment by q52888940** [comment]
其他无线电都很正常，但在胜利时他说我未绑定？

**Comment by q52888940** [comment]
![de_dust0000](https://user-images.githubusercontent.com/68973128/126534551-4659f49f-d2d4-47a9-93b5-e50d9622b06c.jpg)

**Comment by q52888940** [comment]
已解决
