### ISSUE TITLE
字幕一直未被找到

### ISSUE THREAD

**Issue by q52888940** [hzqst/CaptionMod#15]
控制台,
CaptionMod: TextMessage [#Hint_lost_money] not found.
![S72VFXKVDVAE}CU5}WTD9GA](https://user-images.githubusercontent.com/68973128/126543245-7e313dbe-6d0b-4888-b545-16f54c54d120.png)
我无论如何填写都无法找到此项目 请告诉我格式

**Comment by q52888940** [comment]
are you still there

**Comment by hzqst** [comment]
你有试过吧#Hint_lost_money改成Hint_lost_money吗？

**Comment by q52888940** [comment]
是的 我尝试过 不止一次,我的版本号是 
Caption Mod 2021-07-20

**Comment by q52888940** [comment]
如果你有空可以解决下这个问题吗

**Comment by q52888940** [comment]
另外cap_reload命令不可用了 导致我每次测试字幕都需要重新进入游戏

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/126640254-d6396822-8320-4a2e-9e5a-08aaa86cb68d.png)
![image](https://user-images.githubusercontent.com/12287588/126640858-73e5bc66-2485-4c11-bd10-d8fd0bd481f8.png)

https://github.com/hzqst/MetaHookSv/commit/fc812cefb4f432014928e5f4064a25bf12aa6500

应该已经修复，CaptionMod以后不在这边更新了，都迁移到那边。
