### ISSUE TITLE
Apostrophe

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/CaptionMod#4]
Sometimes apostrophe is placed weirdly. 
 For example:
It's messy so don
<new line>
't go over there

**Comment by hzqst** [comment]
https://github.com/hzqst/CaptionMod/blob/0a7f32e33a1c6d30da5e65a2e0a8c38b815ed147/MetaHook/Plugins/CaptionMod/SubtitlePanel.cpp#L411

changed to

https://github.com/hzqst/CaptionMod/blob/8b18dc6ad19ccb962b31306a7ca8ebf65a1dfc0f/MetaHook/Plugins/CaptionMod/SubtitlePanel.cpp#L411

It should solve the issue.

**Comment by qabRieL99** [comment]
Thank you. By the way, those updates should be applied to words as well. Also, comma and dot can be updated as well.
