### ISSUE TITLE
Use Steam language instead of game's language

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/CaptionMod#6]
This feature is neccessary as the game supports only limited number of languages, and to be able to use a language that's not available by the game.

**Comment by hzqst** [comment]
if you want to add an unsupport language translation for third-party game you could just translate all *_english.txt files.

**Comment by qabRieL99** [comment]
Even Half-Life itself supports 9 languages. Say you wanted to translate it into Icelandic or Bulgarian, then you lose the ability to play the game in original language when you wanted to. That defeats the whole purpose of multi-language support.

**Comment by qabRieL99** [comment]
Hey, could you could tell me how to achieve this? I mean I'd like to use the language of the Steam instead of the game itself.
