### ISSUE TITLE
Dots and commas are still breaking.

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/CaptionMod#7]
Dots and commas don't behave as they should even with https://github.com/hzqst/CaptionMod/commit/006af50d60869c0b2ed5290e619b8a8994f0bc9d is applied.
An example looks like this:
**Original line:** `The borderworld, Xen, is in our control for the time being, thanks to you.`
**Cut line:** `The borderworld, Xen, is in our control for the time being`
**Cut line cont'd:** `, thanks to you.`

**Comment by hzqst** [comment]
What's the correct result looks like for the given example?

**Comment by qabRieL99** [comment]
It should be:
**Cut line:** `The borderworld, Xen, is in our control for the time`
**Cut line cont'd:** `being, thanks to you.`

**Comment by qabRieL99** [comment]
Hi there. It's me again. This issue still happens. Here are some examples:

1. The line for reference:
`The first move we will practice in the hazard course is basic jumping. You will attempt to get over this set of pipes, using only your run and jump commands. It helps to get a running start. Watch me and then try it yourself.`
![1](https://user-images.githubusercontent.com/64584999/103408938-9c45a980-4b75-11eb-8b7c-30316df862e0.jpg)
![2](https://user-images.githubusercontent.com/64584999/103408968-c008ef80-4b75-11eb-821e-544b83c0549d.jpg)

2. The line for reference:
`What you really need to do is push that box down into the pit. Pushing is easy. Just move forward against the box and you can push it into position.`
![3](https://user-images.githubusercontent.com/64584999/103409040-03fbf480-4b76-11eb-982e-3c68b78fd321.jpg)
![4](https://user-images.githubusercontent.com/64584999/103409042-052d2180-4b76-11eb-80c8-2e93422bcd14.jpg)

3. The line for reference:
`Great! Remember, your flashlight drains power, so switch it off, when you don't need it.`
![5](https://user-images.githubusercontent.com/64584999/103409072-2726a400-4b76-11eb-8423-6c725bfaa54f.jpg)
![6](https://user-images.githubusercontent.com/64584999/103409077-2aba2b00-4b76-11eb-8f0a-f83df474a2a1.jpg)

I'm not fluent in C++, so I decided I'd play around with the code. So I changed the existing part of this code:
https://github.com/hzqst/CaptionMod/blob/36ca12818e945cd67bbb06d5cace5d8021af7c16/MetaHook/Plugins/CaptionMod/SubtitlePanel.cpp#L410-L428

to this:
![image](https://user-images.githubusercontent.com/64584999/103409248-f5faa380-4b76-11eb-94d0-15a30c47127c.png)
In which I just got rid of the else if part and merged the symbols with letters.
For a while, it seemed like the problem was solved:
![20201231142211_1](https://user-images.githubusercontent.com/64584999/103409283-27736f00-4b77-11eb-8e61-fed40fc7d0d1.jpg)
![20201231142358_1](https://user-images.githubusercontent.com/64584999/103409284-28a49c00-4b77-11eb-98b0-b8d059853f91.jpg)
![20201231142504_1](https://user-images.githubusercontent.com/64584999/103409286-293d3280-4b77-11eb-83e7-f9aa367be8e6.jpg)

Seems fine, right? But after some time, I noticed weird behaviours in some other strings, which were working perfectly fine before:
![20201231142422_1](https://user-images.githubusercontent.com/64584999/103409307-44a83d80-4b77-11eb-98b6-665caf4643ae.jpg)
![20201231142141_1](https://user-images.githubusercontent.com/64584999/103409308-45d96a80-4b77-11eb-91cc-e108f999d80a.jpg)

I'd really appreciate if you could take a look.

**Comment by hzqst** [comment]
try:
SubtitlePanel.cpp line 413
`while((*p >= L'A' && *p <= L'Z') || (*p >= L'a' && *p <= L'z'))`

to

`while((*p >= L'A' && *p <= L'Z') || (*p >= L'a' && *p <= L'z') || *p == L'.' || *p == L',' || *p == L':')`

**Comment by qabRieL99** [comment]
> try:
> SubtitlePanel.cpp line 413
> `while((*p >= L'A' && *p <= L'Z') || (*p >= L'a' && *p <= L'z'))`
> 
> to
> 
> `while((*p >= L'A' && *p <= L'Z') || (*p >= L'a' && *p <= L'z') || *p == L'.' || *p == L',' || *p == L':')`

Hey, thanks for answering. I did that, but the result is the same with these two images:
![20201231142422_1](https://user-images.githubusercontent.com/64584999/103409307-44a83d80-4b77-11eb-98b6-665caf4643ae.jpg)
![20201231142141_1](https://user-images.githubusercontent.com/64584999/103409308-45d96a80-4b77-11eb-91cc-e108f999d80a.jpg)
Now it just doesn't fit the border.

**Comment by qabRieL99** [comment]
Here are few more examples:
![20201231155923_1](https://user-images.githubusercontent.com/64584999/103411918-c69e6380-4b83-11eb-8021-336eb6b82a96.jpg)
![20201231160055_1](https://user-images.githubusercontent.com/64584999/103411920-c8682700-4b83-11eb-8bf4-6648a685c1aa.jpg)

**Comment by hzqst** [comment]
> Here are few more examples:
> ![20201231155923_1](https://user-images.githubusercontent.com/64584999/103411918-c69e6380-4b83-11eb-8021-336eb6b82a96.jpg)
> ![20201231160055_1](https://user-images.githubusercontent.com/64584999/103411920-c8682700-4b83-11eb-8bf4-6648a685c1aa.jpg)

Could you provide the dictionary file and localization files so I can debug the issue?

**Comment by qabRieL99** [comment]
[CaptionMod.zip](https://github.com/hzqst/CaptionMod/files/5759914/CaptionMod.zip)
Here it is.

**Comment by hzqst** [comment]
I've fixed the issue in c1a0_sci_lock1a "I'm afraid we'll be deviating a bit from standard analysis procedures today, Gordon."
by adjusting the order of execution with "out of range check"
at SubtitlePanel.cpp&line430
```
			//It's out of range? go back to last position and make it a new line
			if(nWide > iMaxTextWidth)
			{
				nWide = nLastWide;
				nCharNum = nLastCharNum;
				p = LastP;
				nAddedCharNum += nCharNum;
				break;
			}

			//Force to be a new line
			if (*p == L'\0' || *p == L'\n' || *p == L'\r')
			{
				nAddedCharNum += nCharNum;
				break;
			}
```


https://user-images.githubusercontent.com/12287588/103472507-6f89d000-4dc9-11eb-9f4f-149d5c401c21.mp4

BTW can you provide non-ASCII english characters/symbols like 
![image](https://user-images.githubusercontent.com/12287588/103472641-9a285880-4dca-11eb-8c83-1f293d9451cd.png)
so I can merge them into master branch.

**Comment by qabRieL99** [comment]
Hi, in my case, they're: Ç ç Ğ ğ İ ı Ö ö Ş ş Ü ü Â â. But that's just for my language.
